dbt_project_1:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dbt-airflow-postgres-1
      user: airflow
      password: airflow
      port: 5432
      dbname: dbt_db # or database instead of dbname
      schema: dbt_schema
